config/routes.rb
Rails.application.routes.draw do
  resources :consulta
  resources :tipos
  resources :racas
  devise_for :users
  root to: redirect('/animals')
  resources :animals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tipo.rb
class Tipo < ApplicationRecord
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]

  # GET /tipos
  # GET /tipos.json
  def index
    @tipos = Tipo.all
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
    authorize! :manage, @tipo
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
    authorize! :manage, @tipo
  end

  # POST /tipos
  # POST /tipos.json
  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, notice: 'Tipo was successfully created.' }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos/1
  # PATCH/PUT /tipos/1.json
  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to @tipo, notice: 'Tipo was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url, notice: 'Tipo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_params
      params.require(:tipo).permit(:descricao)
    end
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/tipos/_form.html.erb
<%= form_for(tipo) do |f| %>
  <% if tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipo.errors.count, "error") %> prohibited this tipo from being saved:</h2>

      <ul>
      <% tipo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %>
    <%= f.text_field :descricao %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipos/edit.html.erb
<h1>Editing Tipo</h1>

<%= render 'form', tipo: @tipo %>

<%= link_to 'Show', @tipo %> |
<%= link_to 'Back', tipos_path %>

app/views/tipos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipos</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipos.each do |tipo| %>
      <tr>
        <td><%= tipo.descricao %></td>
        <td><%= link_to 'Show', tipo %></td>
        <td><%= link_to 'Edit', edit_tipo_path(tipo) %></td>
        <td><%= link_to 'Destroy', tipo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo', new_tipo_path %>

app/views/tipos/new.html.erb
<h1>New Tipo</h1>

<%= render 'form', tipo: @tipo %>

<%= link_to 'Back', tipos_path %>

app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @tipo.descricao %>
</p>

<%= link_to 'Edit', edit_tipo_path(@tipo) %> |
<%= link_to 'Back', tipos_path %>