config/routes.rb
Rails.application.routes.draw do
  resources :consulta
  resources :tipos
  resources :racas
  devise_for :users
  root to: redirect('/animals')
  resources :animals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord

  belongs_to :user
  has_many :consulta

  belongs_to :tipo
  belongs_to :raca

  validates_presence_of :nome

  mount_uploader :foto, PictureUploader

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
    authorize! :manage, @animal
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
    authorize! :manage, @animal
  end

  # POST /animals
  # POST /animals.json
  def create
    @user = current_user
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:nome, :nascimento, :sexo, :pelagem, :tipo_id, :raca_id, :user_id, :foto)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_for(animal) do |f| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :birth %>
    <%= f.date_select :nascimento, start_year: Date.today.year - 30, end_year: Date.today.year %>
  </div>

  <div class="field">
    <%= f.label :sex %>
    <%= f.select :sexo, [['Male'], ['Female']] %>
  </div>

  <div class="field">
    <%= f.label :fur %>
    <%= f.text_field :pelagem %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.collection_select :tipo_id, Tipo.order(:descricao), :id, :descricao %>
  </div>

  <div class="field">
    <%= f.label :breed %>
    <%= f.collection_select :raca_id, Raca.order(:descricao), :id, :descricao %>
    <%-# f.grouped_collection_select :raca_id, Tipo.order(:descricao), :racas, :descricao, :id, :descricao, include_blank: true -%>
  </div>

  <div class="field">
    <%= f.label :owner %>
    <%= f.collection_select :user_id, User.order(:email), :id, :email %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :foto %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animals</h1>
<%= flash[:alert] %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birth</th>
      <th>Sex</th>
      <th>Fur</th>
      <th>Type</th>
      <th>Breed</th>
      <th>Owner</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <% if can? :manage, animal %>
        <tr>
          <td><%= animal.nome %></td>
          <td><%= animal.nascimento.strftime("%m/%d/%Y") %></td>
          <td><%= animal.sexo %></td>
          <td><%= animal.pelagem %></td>
          <td><%= animal.tipo.descricao %></td>
          <td><%= animal.raca.descricao %></td>
          <td><%= animal.user.email %></td>
          <td><%= image_tag(animal.foto_url, width: 100) if animal.foto.present? %></td>
          <td><%= link_to 'Show', animal %></td>
          <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
          <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @animal.nome %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @animal.nascimento.strftime("%m/%d/%Y") %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @animal.sexo %>
</p>

<p>
  <strong>Fur:</strong>
  <%= @animal.pelagem %>
</p>

<p>
  <strong>Type:</strong>
  <%= @animal.tipo.descricao %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @animal.raca.descricao %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @animal.user.email %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@animal.foto_url, width: 100) if @animal.foto.present? %>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>