config/routes.rb
Rails.application.routes.draw do
  resources :consulta
  resources :tipos
  resources :racas
  devise_for :users
  root to: redirect('/animals')
  resources :animals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/raca.rb
class Raca < ApplicationRecord
end

app/controllers/racas_controller.rb
class RacasController < ApplicationController
  before_action :set_raca, only: [:show, :edit, :update, :destroy]

  # GET /racas
  # GET /racas.json
  def index
    @racas = Raca.all
  end

  # GET /racas/1
  # GET /racas/1.json
  def show
    authorize! :manage, @raca
  end

  # GET /racas/new
  def new
    @raca = Raca.new
  end

  # GET /racas/1/edit
  def edit
    authorize! :manage, @raca
  end

  # POST /racas
  # POST /racas.json
  def create
    @raca = Raca.new(raca_params)

    respond_to do |format|
      if @raca.save
        format.html { redirect_to @raca, notice: 'Raca was successfully created.' }
        format.json { render :show, status: :created, location: @raca }
      else
        format.html { render :new }
        format.json { render json: @raca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /racas/1
  # PATCH/PUT /racas/1.json
  def update
    respond_to do |format|
      if @raca.update(raca_params)
        format.html { redirect_to @raca, notice: 'Raca was successfully updated.' }
        format.json { render :show, status: :ok, location: @raca }
      else
        format.html { render :edit }
        format.json { render json: @raca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /racas/1
  # DELETE /racas/1.json
  def destroy
    @raca.destroy
    respond_to do |format|
      format.html { redirect_to racas_url, notice: 'Raca was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_raca
      @raca = Raca.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def raca_params
      params.require(:raca).permit(:descricao)
    end
end

app/helpers/racas_helper.rb
module RacasHelper
end

app/views/racas/_form.html.erb
<%= form_for(raca) do |f| %>
  <% if raca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(raca.errors.count, "error") %> prohibited this raca from being saved:</h2>

      <ul>
      <% raca.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descricao %>
    <%= f.text_field :descricao %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/racas/edit.html.erb
<h1>Editing Raca</h1>

<%= render 'form', raca: @raca %>

<%= link_to 'Show', @raca %> |
<%= link_to 'Back', racas_path %>

app/views/racas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Racas</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @racas.each do |raca| %>
      <tr>
        <td><%= raca.descricao %></td>
        <td><%= link_to 'Show', raca %></td>
        <td><%= link_to 'Edit', edit_raca_path(raca) %></td>
        <td><%= link_to 'Destroy', raca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Raca', new_raca_path %>

app/views/racas/new.html.erb
<h1>New Raca</h1>

<%= render 'form', raca: @raca %>

<%= link_to 'Back', racas_path %>

app/views/racas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @raca.descricao %>
</p>

<%= link_to 'Edit', edit_raca_path(@raca) %> |
<%= link_to 'Back', racas_path %>