config/routes.rb
Rails.application.routes.draw do
  resources :consulta
  resources :tipos
  resources :racas
  devise_for :users
  root to: redirect('/animals')
  resources :animals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/consulta_controller.rb
class ConsultaController < ApplicationController
  before_action :set_consultum, only: [:show, :edit, :update, :destroy]

  # GET /consulta
  # GET /consulta.json
  def index
    @consulta = Consultum.all
  end

  # GET /consulta/1
  # GET /consulta/1.json
  def show
    authorize! :manage, @consultum
  end

  # GET /consulta/new
  def new
    @consultum = Consultum.new
  end

  # GET /consulta/1/edit
  def edit
    authorize! :manage, @consultum
  end

  # POST /consulta
  # POST /consulta.json
  def create
    @consultum = Consultum.new(consultum_params)

    respond_to do |format|
      if @consultum.save
        format.html { redirect_to @consultum, notice: 'Consultum was successfully created.' }
        format.json { render :show, status: :created, location: @consultum }
      else
        format.html { render :new }
        format.json { render json: @consultum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consulta/1
  # PATCH/PUT /consulta/1.json
  def update
    respond_to do |format|
      if @consultum.update(consultum_params)
        format.html { redirect_to @consultum, notice: 'Consultum was successfully updated.' }
        format.json { render :show, status: :ok, location: @consultum }
      else
        format.html { render :edit }
        format.json { render json: @consultum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consulta/1
  # DELETE /consulta/1.json
  def destroy
    @consultum.destroy
    respond_to do |format|
      format.html { redirect_to consulta_url, notice: 'Consultum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultum
      @consultum = Consultum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consultum_params
      params.require(:consultum).permit(:motivo, :dia, :horario, :user_id, :animal_id)
    end
end

app/helpers/consulta_helper.rb
module ConsultaHelper
end

app/views/consulta/_form.html.erb
<%= form_for(consultum) do |f| %>
  <% if consultum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consultum.errors.count, "error") %> prohibited this consultum from being saved:</h2>

      <ul>
      <% consultum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reason %>
    <%= f.text_field :motivo %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :dia, start_year: Date.today.year, end_year: Date.today.year + 30 %>
  </div>

  <div class="field">
    <%= f.label :time %>
    <%= f.time_select :horario %>
  </div>

  <div class="field">
    <%= f.label :client %>
    <%= f.collection_select :user_id, User.order(:email), :id, :email %>
  </div>

  <div class="field">
    <%= f.label :pacient %>
    <%= f.collection_select :animal_id, Animal.order(:nome), :id, :nome %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consulta/edit.html.erb
<h1>Editing Consultum</h1>

<%= render 'form', consultum: @consultum %>

<%= link_to 'Show', @consultum %> |
<%= link_to 'Back', consulta_path %>

app/views/consulta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Reason</th>
      <th>Date</th>
      <th>Time</th>
      <th>Client</th>
      <th>Pacient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consulta.each do |consultum| %>
      <% if can? :manage, consultum %>
        <tr>
          <td><%= consultum.motivo %></td>
          <td><%= consultum.dia.strftime("%m/%d/%Y") %></td>
          <td><%= consultum.horario.strftime("%H:%M") %></td>
          <td><%= consultum.user.email %></td>
          <td><%= consultum.animal.nome %></td>
          <td><%= link_to 'Show', consultum %></td>
          <td><%= link_to 'Edit', edit_consultum_path(consultum) %></td>
          <td><%= link_to 'Destroy', consultum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_consultum_path %>

app/views/consulta/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', consultum: @consultum %>

<%= link_to 'Back', consulta_path %>

app/views/consulta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Reason:</strong>
  <%= @consultum.motivo %>
</p>

<p>
  <strong>Date:</strong>
  <%= @consultum.dia.strftime("%m/%d/%Y") %>
</p>

<p>
  <strong>Time:</strong>
  <%= @consultum.horario.strftime("%H:%M") %>
</p>

<p>
  <strong>Client:</strong>
  <%= @consultum.user.email %>
</p>

<p>
  <strong>Pacient:</strong>
  <%= @consultum.animal.nome %>
</p>

<%= link_to 'Edit', edit_consultum_path(@consultum) %> |
<%= link_to 'Back', consulta_path %>